<?php
require 'header.php';
?>

    <div id="heading">
        <h1>THIS</h1>
    </div>

    <div class="contentHeading">
        <h2>Text</h2>
    </div>

    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>
    <p>AAAAAAAAAAAAAAAAA</p>

<?php
require 'footer.php';
?>